### ISSUE TITLE
Incorporate check for CSCvw24269 UCS Firmware Bundles Greater Than 2GB May Fail to Extract

### ISSUE THREAD

**Issue by riaanvn** [CiscoDevNet/ucsm_health_check#2]
Please expand the script to indicate if bug
https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw24269 
UCS Firmware Bundles Greater Than 2GB May Fail to Extract
is applicable when upgrading a 6400-series to 4.2(il) or later and the source infra bundle firmware version is not at a high enough level?

**Comment by AkashMalla1** [comment]
Hi Riaan, thank you for your feedback, will definitely review it in future releases.
