### ISSUE TITLE
Feature request: provide switches that allow for non-interactive use

### ISSUE THREAD

**Issue by riaanvn** [CiscoDevNet/ucsm_health_check#7]
Currently, the script runs interactively only, e.g. it is cumbersome to run against a large number of tech support bundles, especially having to supply the full file path.

Suggestion - add command-line switches that would allow for non-interactive use:
(not sure if long/short switches are supported

-p / --filepath
-h / --health
-u / --preupgrade
-t / --target (assuming this would have to be double/single quoted due to the round brackets)

**Comment by AkashMalla1** [comment]
Thank you for your suggestion, currently the script only runs on the UCSM tech support bundles and has been designed that way. Any further development will be updated over https://www.cisco.com/c/en/us/support/docs/servers-unified-computing/ucs-infrastructure-ucs-manager-software/217601-ucsm-health-and-pre-upgrade-check-tool.html

**Comment by riaanvn** [comment]
I don't understand what you are saying. Maybe you misunderstood me. I know the script runs against UCSM tech support bundles. However, if one wants to run it against multiple UCSM tech support bundles, using it interactively is very cumbersome. 

Many commands, scripts and have command-line switches and options which allow for non-interactive use.

Can you please re-open the issue?

**Comment by monahancj** [comment]
I would like this, too.  I already pull tech support files from the command line.  If I could use this tool on the command line I could automate some pre-upgrade steps.  Maybe run it daily and compare outputs for changes.
