### ISSUE TITLE
Feature request: Include the domain name in the UCS_Report output directory name

### ISSUE THREAD

**Issue by riaanvn** [CiscoDevNet/ucsm_health_check#8]
Currently, the output directory looks like this

UCS_Report_2022_11_04_11_32_31

This makes it very difficult to separate the reports for multiple domains. Add the file name against which the script was run, will make it a lot easier to tell multiple reports apart, e.g.

If the input file was 20221029154016_LAB1_UCSM.tar

The directory becomes

20221029154016_LAB1_UCSM-UCS_Report_2022_11_04_11_32_31
OR
UCS_Report_2022_11_04_11_32_31-20221029154016_LAB1_UCSM

**Comment by AkashMalla1** [comment]
Will be taken care in next release, thank you for the feature suggestion.

**Comment by riaanvn** [comment]
Can you please re-open the issue? 

a) it is customary to keep an issue open until the issue is actually fixed, not based on a promise that it will be fixed in future:
https://docs.github.com/en/enterprise-cloud@latest/issues/tracking-your-work-with-issues/closing-an-issue#
b) other users that have the same requirement, and do not see this as an open issue, will re-log, creating duplication.
